"""reading unique meter period

Revision ID: 7879ab936a9a
Revises: a058bbc27f26
Create Date: 2026-08-20 16:27:59.003875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7879ab936a9a'
down_revision: Union[str, None] = 'a058bbc27f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Защита от существующих дублей перед созданием уникального ограничения:
    # оставляем самую свежую запись по (meter_id, period), лишние удаляем.
    # Безопасно и для чистой БД (ничего не удаляет, если дублей нет).
    bind = op.get_bind()
    bind.exec_driver_sql(
        """
        DELETE FROM reading
        WHERE id NOT IN (
            SELECT keep_id FROM (
                SELECT MAX(id) AS keep_id
                FROM reading
                GROUP BY meter_id, period
            ) AS keepers
        )
        """
    )
    with op.batch_alter_table('reading', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_reading_meter_period', ['meter_id', 'period'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reading_meter_period', type_='unique')

    # ### end Alembic commands ###
