"""initial schema

Revision ID: a058bbc27f26
Revises: 
Create Date: 2026-08-20 16:25:10.658603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a058bbc27f26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sa.Enum('FULL', 'PARTIAL', 'BUG', 'IDEA', name='feedbackscope'), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'NEEDS_CLARIFICATION', 'READY_FOR_REVIEW', 'DONE', 'REJECTED', name='feedbackstatus'), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meter_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('WATER', 'ENERGY', 'GAS', 'HEAT', 'OTHER', name='metercategory'), nullable=False),
    sa.Column('name_lv', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('max_plausible_consumption', sa.Float(), nullable=False),
    sa.Column('allow_zero_consumption', sa.Boolean(), nullable=False),
    sa.Column('field_schema', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meter_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meter_type_code'), ['code'], unique=True)

    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reg_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brand_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reading_day_from', sa.Integer(), nullable=False),
    sa.Column('reading_day_to', sa.Integer(), nullable=False),
    sa.Column('integration_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('integration_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_slug'), ['slug'], unique=True)

    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_building_organization_id'), ['organization_id'], unique=False)

    op.create_table('feedback_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Enum('MODERATOR', 'AGENT', name='feedbackauthor'), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['feedback_thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_message_thread_id'), ['thread_id'], unique=False)

    op.create_table('integration_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_log_organization_id'), ['organization_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('SUPERADMIN', 'MANAGER', 'RESIDENT', name='userrole'), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_organization_id'), ['organization_id'], unique=False)

    op.create_table('feedback_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stored_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['feedback_message.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['feedback_thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_attachment_thread_id'), ['thread_id'], unique=False)

    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('residents_count', sa.Integer(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_building_id'), ['building_id'], unique=False)

    op.create_table('meter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('meter_type_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('initial_value', sa.Float(), nullable=False),
    sa.Column('installed_on', sa.Date(), nullable=True),
    sa.Column('verification_due', sa.Date(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['meter_type_id'], ['meter_type.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meter_meter_type_id'), ['meter_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_unit_id'), ['unit_id'], unique=False)

    op.create_table('unit_resident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('relation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'unit_id')
    )
    with op.batch_alter_table('unit_resident', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_resident_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_resident_user_id'), ['user_id'], unique=False)

    op.create_table('reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('consumption', sa.Float(), nullable=True),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('WEB', 'MANAGER', 'IMPORT', 'ESTIMATED', 'METER_OPERATOR', name='readingsource'), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'ACCEPTED', 'SYNCED', 'REJECTED', name='readingstatus'), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meter.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_meter_id'), ['meter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_period'), ['period'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_period'))
        batch_op.drop_index(batch_op.f('ix_reading_meter_id'))

    op.drop_table('reading')
    with op.batch_alter_table('unit_resident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_resident_user_id'))
        batch_op.drop_index(batch_op.f('ix_unit_resident_unit_id'))

    op.drop_table('unit_resident')
    with op.batch_alter_table('meter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meter_unit_id'))
        batch_op.drop_index(batch_op.f('ix_meter_meter_type_id'))

    op.drop_table('meter')
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_building_id'))

    op.drop_table('unit')
    with op.batch_alter_table('feedback_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_attachment_thread_id'))

    op.drop_table('feedback_attachment')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_organization_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('integration_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_log_organization_id'))

    op.drop_table('integration_log')
    with op.batch_alter_table('feedback_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_message_thread_id'))

    op.drop_table('feedback_message')
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_building_organization_id'))

    op.drop_table('building')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_slug'))

    op.drop_table('organization')
    with op.batch_alter_table('meter_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meter_type_code'))

    op.drop_table('meter_type')
    op.drop_table('feedback_thread')
    # ### end Alembic commands ###
